### ISSUE TITLE
s3 transport not working with AWS auth v4

### ISSUE THREAD

**Issue by vorlock** [BashtonLtd/apt-transport-s3#10]
Reported by user (Mihai):

```
I want to signal the fact that "apt-transport-s3" does not work with buckets created in the Frankfurt region. That’s because of the new v4 authorization mechanism that the Frankfurt region uses solely.
```

Need confirmation and fix

**Comment by gdhbashton** [comment]
+1 - a certain cinematic customer would really enjoy having this fixed :)

**Comment by JamieCressey** [comment]
I think I ran into this problem too when attempting to connect to cn-north-1.

I've made a slightly opinionated fork (https://github.com/JamieCressey/apt-transport-s3/commit/6867f809360f041d692f1a494f011a780b2bbc8f) which should fix this, as it communicates with S3 via Boto3.

I'm happy to submit a PR with these changes in, but they include a number of breaking changes as things stand; 
1) Moving key/secret pairs from s3auth.conf to ~/.aws/credentials
2) Moving regional settings (FQDN on the bucket name) from apt source list to ~/.aws/config
3) Dropped IAM role support (this was slightly unintentional, and should be simple to put back)

**Comment by hfink** [comment]
+1 - as a newbie I got "400 Bad Request" responses until I used a different location than Frankfurt (now using Ireland instead).

**Comment by filip-vt** [comment]
Same behaviour in China region

**Comment by SonOfBytes** [comment]
@vorlock @gdhbashton @hfink @filip-vt - It's in early testing and it uses a slightly different conf setup so not a non-breaking change.  But added support for v4 sigs without using both here.

https://github.com/SonOfBytes/apt-transport-s3

**Comment by ajlanghorn** [comment]
Support for this has been merged in to the master branch as of this morning, so this bug can probably be closed.
