### ISSUE TITLE
Unable to have multiple keys in S3auth.conf

### ISSUE THREAD

**Issue by Yokai** [BashtonLtd/apt-transport-s3#18]
I have several separate buckets that are set up with specific keys.
This is so that builds from an apt-repo cannot get mistakenly added by sales eng, the customer, dev etc.

It seems impossible to configure S3auth.conf in a way to separate this out...  Am I missing something because this was clearly doable in 14.04

**Comment by vorlock** [comment]
To be honest I'm not sure how it worked with multiply keys as it's never being designed nor implemented to support such behaviour.

ConfigObj is used to read s3auth.conf, so I'd assume that if you've got multiply secret and  access keys last appearance of each is used but I think that I need to add some checks and warnings to ensure that last one is used.

Probably implementing multiply keys on repo base would require some kind of tagging in the apt.sources config but right now I'm not sure yet how to do it.

**Comment by Yokai** [comment]
@vorlock - Thanks
