### ISSUE TITLE
Newest ubuntu python updates bring in changes that break apt-transport-s3

### ISSUE THREAD

**Issue by pcn** [BashtonLtd/apt-transport-s3#22]
I've run into a failure to use some buckets after an upgrade of ubuntu that worked prior.  The end result is this:

```
ValueError: Invalid header value 'AWS ASIAII[XXXetc.]:[more XXX\ etc.]=\n'
```

I've seen mention of issues with newlines in headers in python https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1644287 (identical to what I'm seeing) and it seems like there was something related in ansible: https://github.com/ansible/ansible-modules-core/issues/2353#issuecomment-231858865.

I'm not sure yet what to do which would address this, I'm going to read the update.

**Comment by pcn** [comment]
Never mind, we're out of date.  Fixed  in https://github.com/BashtonLtd/apt-transport-s3/commit/5b41a8385216a9e9bd7db793d5f6758b465edc0b

**Comment by koldsco** [comment]
FWIW I ran into this problem last week, and did a cheap and dirty hack:

diff s3-orig s3
170c170
<         signature = self.sign(request)
---
>         signature = self.sign(request).strip()


that got it working for me again. If you are interested in rewriting this python3 and boto3, I would like to lend a hand, in any capacity that might be helpful.

----

I see you have fixed it in much the same way.
